//
//  BeerListPresenterTests.swift
//  uol-beer-app
//
//  Created by Paulo Lourenço on 12/04/19.
//  Copyright (c) 2019 Paulo Lourenço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import uol_beer_app
import XCTest

class BeerListDisplayLogicSpy: BeerListDisplayLogic {
    var calledDisplayBeers = false
    var calledDisplayBeerDetails = false
    var calledShowError = false
    
    func displayBeers() {
        calledDisplayBeers = true
    }
    
    func displayBeerDetails() {
        calledDisplayBeerDetails = true
    }
    
    func showError(title: String?, message: String?, tryAgainAction: (() -> Void)?) {
        calledShowError = true
    }
}

class BeerListPresenterTests: XCTestCase {
    
    // MARK: Subject under test
    
    var sut: BeerListPresenter!
    var viewControllerSpy: BeerListDisplayLogicSpy!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        sut = BeerListPresenter()
        viewControllerSpy = BeerListDisplayLogicSpy()
    }
    
    override func tearDown() {
        super.tearDown()
        sut = nil
    }
    
    // MARK: Tests
    
    func testPresentBeers() {
        sut.viewController = viewControllerSpy
        sut.presentBeers()
        
        XCTAssertTrue(viewControllerSpy.calledDisplayBeers)
    }
    
    func testPresentBeerDetails() {
        sut.viewController = viewControllerSpy
        sut.presentBeerDetails()
        
        XCTAssertTrue(viewControllerSpy.calledDisplayBeerDetails)
    }
    
    func testPresentError() {
        sut.viewController = viewControllerSpy
        sut.presentError(error: APIClient.Errors.errorStatusCode(400), tryAgainAction: nil)
        
        XCTAssertTrue(viewControllerSpy.calledShowError)
    }
    
}
