//
//  BeerDetailsModels.swift
//  uol-beer-app
//
//  Created by Paulo Lourenço on 11/04/19.
//  Copyright (c) 2019 Paulo Lourenço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BeerDetails {
    // MARK: Use cases
    
    struct Request {
    }
    
    struct Response {
        var beer: Beer
    }
    
    struct ViewModel {
        var imageUrl: URL?
        var name: String
        var tagline: String
        var details: String?
    }
    
}
