//
//  BeerDetailsInteractor.swift
//  uol-beer-app
//
//  Created by Paulo Lourenço on 11/04/19.
//  Copyright (c) 2019 Paulo Lourenço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BeerDetailsBusinessLogic {
    func getDetails()
}

protocol BeerDetailsDataStore {
    var beer: Beer? { get set }
}

class BeerDetailsInteractor: BeerDetailsBusinessLogic, BeerDetailsDataStore {
    var presenter: BeerDetailsPresentationLogic?
    var worker: BeerDetailsWorker?
    
    var beer: Beer?
    
    func getDetails() {
        guard let beer = beer else { return }
        presenter?.presentDetails(response: BeerDetails.Response(beer: beer))
    }
}
