//
//  BeerDetailsViewController.swift
//  uol-beer-app
//
//  Created by Paulo Lourenço on 11/04/19.
//  Copyright (c) 2019 Paulo Lourenço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SDWebImage

protocol BeerDetailsDisplayLogic: class {
    func displayDetails(viewModel: BeerDetails.ViewModel)
}

class BeerDetailsViewController: UIViewController {
    
    // MARK: Clean Swift
    
    var interactor: BeerDetailsBusinessLogic?
    var router: (NSObjectProtocol & BeerDetailsRoutingLogic & BeerDetailsDataPassing)?
    
    // MARK: IBOutlets
    
    @IBOutlet weak var imageView: UIImageView!
    @IBOutlet weak var taglineLabel: UILabel!
    @IBOutlet weak var detailsLabel: UILabel!
    
    // MARK: Properties
    
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = BeerDetailsInteractor()
        let presenter = BeerDetailsPresenter()
        let router = BeerDetailsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor?.getDetails()
    }
    
}

extension BeerDetailsViewController: BeerDetailsDisplayLogic  {
    
    func displayDetails(viewModel: BeerDetails.ViewModel) {
        navigationItem.title = viewModel.name
        imageView.sd_setImage(with: viewModel.imageUrl, completed: nil)
        taglineLabel.text = viewModel.tagline
        detailsLabel.text = viewModel.details
    }
    
}
