//
//  BeerDetailsInteractor.swift
//  uol-beer-app
//
//  Created by Paulo Lourenço on 11/04/19.
//  Copyright (c) 2019 Paulo Lourenço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BeerDetailsBusinessLogic {
    func doSomething(request: BeerDetails.Something.Request)
}

protocol BeerDetailsDataStore {
    //var name: String { get set }
}

class BeerDetailsInteractor: BeerDetailsBusinessLogic, BeerDetailsDataStore {
    var presenter: BeerDetailsPresentationLogic?
    var worker: BeerDetailsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: BeerDetails.Something.Request) {
        worker = BeerDetailsWorker()
        worker?.doSomeWork()
        
        let response = BeerDetails.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
