//
//  BeerDetailsRouter.swift
//  uol-beer-app
//
//  Created by Paulo Lourenço on 11/04/19.
//  Copyright (c) 2019 Paulo Lourenço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BeerDetailsDataPassing {
    var dataStore: BeerDetailsDataStore? { get }
}

class BeerDetailsRouter: NSObject, BeerDetailsDataPassing {
    weak var viewController: BeerDetailsViewController?
    var dataStore: BeerDetailsDataStore?
}
