//
//  BeerDetailsPresenter.swift
//  uol-beer-app
//
//  Created by Paulo Lourenço on 11/04/19.
//  Copyright (c) 2019 Paulo Lourenço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BeerDetailsPresentationLogic {
    func presentDetails(response: BeerDetails.Response)
}

class BeerDetailsPresenter: BeerDetailsPresentationLogic {
    weak var viewController: BeerDetailsDisplayLogic?
    
    func presentDetails(response: BeerDetails.Response) {
        var details = ""
        if let abv = response.beer.abv {
            details.append("ABV: \(abv)% \n")
        }
        if let ibu = response.beer.ibu {
            details.append("IBU: \(ibu)% \n")
        }
        if let description = response.beer.description {
            details.append("\n\(description)")
        }
        
        let viewModel = BeerDetails.ViewModel(imageUrl: response.beer.imageUrl, name: response.beer.name, tagline: response.beer.tagline, details: details)
        
        viewController?.displayDetails(viewModel: viewModel)
    }
}
