//
//  BeerListRouter.swift
//  uol-beer-app
//
//  Created by Paulo Lourenço on 11/04/19.
//  Copyright (c) 2019 Paulo Lourenço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol BeerListRoutingLogic {
    func handleRoute(segue: UIStoryboardSegue)
    func routeToDetails()
}

protocol BeerListDataPassing {
    var dataStore: BeerListDataStore? { get }
}

class BeerListRouter: NSObject, BeerListRoutingLogic, BeerListDataPassing {
    weak var viewController: BeerListViewController?
    var dataStore: BeerListDataStore?
    
    // MARK: Routing
    
    func routeToDetails() {
        viewController?.performSegue(withIdentifier: "detailsSegue", sender: nil)
    }
    
    func handleRoute(segue: UIStoryboardSegue) {
        if let sourceDS = dataStore,
            let destinationVC = segue.destination as? BeerDetailsViewController,
            var destinationDS = destinationVC.router?.dataStore {
            passDataToDetails(source: sourceDS, destination: &destinationDS)
        }
    }
    
    // MARK: Passing data
    
    func passDataToDetails(source: BeerListDataStore, destination: inout BeerDetailsDataStore) {
        destination.beer = source.selectedBeer
    }

}
