//
//  BeerListPresenter.swift
//  uol-beer-app
//
//  Created by Paulo Lourenço on 11/04/19.
//  Copyright (c) 2019 Paulo Lourenço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BeerListPresentationLogic {
    func presentSomething(response: BeerList.Something.Response)
}

class BeerListPresenter: BeerListPresentationLogic {
    weak var viewController: BeerListDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: BeerList.Something.Response) {
        let viewModel = BeerList.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
