//
//  BeerListPresenter.swift
//  uol-beer-app
//
//  Created by Paulo Lourenço on 11/04/19.
//  Copyright (c) 2019 Paulo Lourenço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BeerListPresentationLogic {
    func presentBeers()
    func presentError(error: Error, tryAgainAction: (()->())?)
}

class BeerListPresenter: BeerListPresentationLogic {
    weak var viewController: BeerListDisplayLogic?
    
    func presentBeers() {
        viewController?.displayBeers()
    }

    func presentError(error: Error, tryAgainAction: (()->())?) {
        viewController?.showError(title: nil, message: error.localizedDescription, tryAgainAction: tryAgainAction)
    }
}
