//
//  BeerListInteractor.swift
//  uol-beer-app
//
//  Created by Paulo Lourenço on 11/04/19.
//  Copyright (c) 2019 Paulo Lourenço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BeerListBusinessLogic {
    func doSomething(request: BeerList.Something.Request)
}

protocol BeerListDataStore {
    //var name: String { get set }
}

class BeerListInteractor: BeerListBusinessLogic, BeerListDataStore {
    var presenter: BeerListPresentationLogic?
    var worker: BeerListWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: BeerList.Something.Request) {
        worker = BeerListWorker()
        worker?.doSomeWork()
        
        let response = BeerList.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
