//
//  BeerListWorker.swift
//  uol-beer-app
//
//  Created by Paulo Lourenço on 11/04/19.
//  Copyright (c) 2019 Paulo Lourenço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit

class BeerListWorker {
    
    var dataSource: BeerAPIDataSource
    
    init(dataSource: BeerAPIDataSource) {
        self.dataSource = dataSource
    }
    
    func getBeers(page: Int? = nil, itemsPerPage: Int? = nil) -> Promise<[Beer]> {
        return dataSource.getBeers(page: page, itemsPerPage: itemsPerPage)
    }
    
}
